# This file holds SENSITIVE values and should NOT be committed once filled.
# Commit ONLY this example file. Each teammate should:
#   1) copy to config/credentials.yml
#   2) paste their tokens + set the single URI
#
# Notes:
# - All projects share the same REDCap API "uri".
# - Each project has its own API "token", keyed by project label.

credentials:
  # One REDCap API endpoint shared by all projects => Please check and update according to redcap.nyu.edu
  uri: "https://redcap.nyu.edu/redcap_v15.0.33/API/"

  # Project tokens keyed by label from config/projects.yml
  tokens:
    youth_baseline: "351C37FEFE1F9E3147A6399E9ED388F2"
    caregiver_baseline: "E1E6D16E5EE0A80CAA81DF5945FF4997"
    youth_followup: "A1CA77BA8C9FB1B668D324F2DBDDCCEC"
    caregiver_followup: "46BCEA1920566BB7B6B9C41DC63C0242"