projects:
  - label: youth_baseline
    events: []
  - label: caregiver_baseline
    events: []
  - label: youth_followup
    events:
      - 3_month_followup_arm_1
      - 6_month_followup_arm_1
  - label: caregiver_followup
    events:
      - 3_month_caregiver_arm_1
      - 6_month_caregiver_arm_1